# Generated by Django 2.1 on 2019-01-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='team')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
