# Generated by Django 2.1 on 2019-01-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190113_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Image',
            field=models.ImageField(upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='Image',
            field=models.ImageField(upload_to='team/'),
        ),
    ]
